global:
  #Change the seconds if needed below:
  scrape_interval: 15s
  evaluation_interval: 15s #alertmanager 

rule_files:
  - alert-rules-exam.yml #alertmanager #Rename of needed

alerting: #alertmanager
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    static_configs:
      - targets:
        - http://gogata05-homies-webapp.azurewebsites.net/ #Change url
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

#alertmanager are for: Set up AlertManager