# Rename: goals - Ctrl+H

version: "3.8"
services:
  mongodb:
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=max
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - goals
    volumes:
      - data:/data/db
    image: mongo
  backend:
    build: ./backend
    networks:
      - goals
    ports:
      - 80:80
    volumes:
      - logs:/logs
      - node_modules:/node_modules
  frontend:
    build: ./frontend
    networks:
      - goals
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/src
networks:
  goals:
volumes:
  data:
  logs:
  node_modules:
